// AUTO-GENERATED. Do not edit by hand.
// Quelle: index.html (Tom BLEYER, 05/2026)

import Foundation

extension ElementsData {
    static let part_61_90: [Element] = [
        Element(z: 61, symbol: "Pm", col: 7, row: 6, category: .lanthanide, nameDE: "Promethium", nameFR: "Prométhium", nameEN: "Promethium", nameLA: "Promethium", protons: 61, neutrons: 84, electrons: 61, mass: 145.0, meltingPointC: 1042, boilingPointC: 3000, stateAt20C: "fest", techApplications: ["Elektrotechnik: Atombatterien (β-Strahler, Forschung)", "Leuchtfarben (historisch)", "Dickenmessgeräte"], compounds: ["Pm₂O₃", "PmCl₃"]),
        Element(z: 62, symbol: "Sm", col: 8, row: 6, category: .lanthanide, nameDE: "Samarium", nameFR: "Samarium", nameEN: "Samarium", nameLA: "Samarium", protons: 62, neutrons: 88, electrons: 62, mass: 150.36, meltingPointC: 1072, boilingPointC: 1794, stateAt20C: "fest", techApplications: ["Elektrotechnik: Samarium-Cobalt-Magnete (SmCo₅) – hochtemperaturstabil in Servomotoren & Luftfahrt", "Nuklearreaktor-Steuerstäbe", "IR-absorbierende Gläser"], compounds: ["Sm₂O₃", "SmCl₃", "SmCo₅"]),
        Element(z: 63, symbol: "Eu", col: 9, row: 6, category: .lanthanide, nameDE: "Europium", nameFR: "Europium", nameEN: "Europium", nameLA: "Europium", protons: 63, neutrons: 89, electrons: 63, mass: 151.96, meltingPointC: 822, boilingPointC: 1529, stateAt20C: "fest", techApplications: ["Elektrotechnik: Rotes Phosphor in Bildschirmen & Energiesparlampen (Y₂O₂S:Eu)", "Sicherheitsmerkmale auf Euro-Banknoten (UV-Fluoreszenz)", "LED-Phosphore"], compounds: ["Eu₂O₃", "EuCl₃"]),
        Element(z: 64, symbol: "Gd", col: 10, row: 6, category: .lanthanide, nameDE: "Gadolinium", nameFR: "Gadolinium", nameEN: "Gadolinium", nameLA: "Gadolinium", protons: 64, neutrons: 93, electrons: 64, mass: 157.25, meltingPointC: 1313, boilingPointC: 3273, stateAt20C: "fest", techApplications: ["Elektrotechnik: MRT-Kontrastmittel", "Nuklearreaktor-Steuerstäbe (hoher Neutroneneinfang)", "Magnetokalorische Materialien", "Speicher-Phosphore"], compounds: ["Gd₂O₃", "GdCl₃"]),
        Element(z: 65, symbol: "Tb", col: 11, row: 6, category: .lanthanide, nameDE: "Terbium", nameFR: "Terbium", nameEN: "Terbium", nameLA: "Terbium", protons: 65, neutrons: 94, electrons: 65, mass: 158.93, meltingPointC: 1359, boilingPointC: 3230, stateAt20C: "fest", techApplications: ["Elektrotechnik: Grüner Phosphor in Leuchtstoffröhren & LEDs", "Magnetostriktive Materialien (Terfenol-D) für Sonarsysteme", "Festkörper-Geräte"], compounds: ["Tb₂O₃", "TbCl₃", "Tb₄O₇"]),
        Element(z: 66, symbol: "Dy", col: 12, row: 6, category: .lanthanide, nameDE: "Dysprosium", nameFR: "Dysprosium", nameEN: "Dysprosium", nameLA: "Dysprosium", protons: 66, neutrons: 97, electrons: 66, mass: 162.5, meltingPointC: 1412, boilingPointC: 2567, stateAt20C: "fest", techApplications: ["Elektrotechnik: Zusatz in Nd-Permanentmagneten für Hochtemperaturbeständigkeit (E-Auto-Motoren, Windkraft)", "Datenspeicher", "Reaktorsteuerung"], compounds: ["Dy₂O₃", "DyCl₃"]),
        Element(z: 67, symbol: "Ho", col: 13, row: 6, category: .lanthanide, nameDE: "Holmium", nameFR: "Holmium", nameEN: "Holmium", nameLA: "Holmium", protons: 67, neutrons: 98, electrons: 67, mass: 164.93, meltingPointC: 1472, boilingPointC: 2700, stateAt20C: "fest", techApplications: ["Elektrotechnik: Polschuhe in Hochfeld-Magneten", "Ho:YAG-Laser für Medizin", "Atomreaktor-Steuerung"], compounds: ["Ho₂O₃", "HoCl₃"]),
        Element(z: 68, symbol: "Er", col: 14, row: 6, category: .lanthanide, nameDE: "Erbium", nameFR: "Erbium", nameEN: "Erbium", nameLA: "Erbium", protons: 68, neutrons: 99, electrons: 68, mass: 167.26, meltingPointC: 1529, boilingPointC: 2868, stateAt20C: "fest", techApplications: ["Elektrotechnik: Erbium-dotierte Glasfaserverstärker (EDFA) in der gesamten Glasfaser-Telekommunikation", "Er:YAG-Laser", "Glas-Färbungen (rosa)"], compounds: ["Er₂O₃", "ErCl₃"]),
        Element(z: 69, symbol: "Tm", col: 15, row: 6, category: .lanthanide, nameDE: "Thulium", nameFR: "Thulium", nameEN: "Thulium", nameLA: "Thulium", protons: 69, neutrons: 100, electrons: 69, mass: 168.93, meltingPointC: 1545, boilingPointC: 1950, stateAt20C: "fest", techApplications: ["Elektrotechnik: Tragbare Röntgenquellen", "Hochleistungs-Faserlaser", "Magnetokeramische Werkstoffe"], compounds: ["Tm₂O₃", "TmCl₃"]),
        Element(z: 70, symbol: "Yb", col: 16, row: 6, category: .lanthanide, nameDE: "Ytterbium", nameFR: "Ytterbium", nameEN: "Ytterbium", nameLA: "Ytterbium", protons: 70, neutrons: 103, electrons: 70, mass: 173.05, meltingPointC: 824, boilingPointC: 1196, stateAt20C: "fest", techApplications: ["Elektrotechnik: Yb-dotierte Faserlaser (Hochleistungslaser für Materialbearbeitung)", "Atomuhren der nächsten Generation", "Drucksensoren"], compounds: ["Yb₂O₃", "YbCl₃"]),
        Element(z: 71, symbol: "Lu", col: 17, row: 6, category: .lanthanide, nameDE: "Lutetium", nameFR: "Lutécium", nameEN: "Lutetium", nameLA: "Lutetium", protons: 71, neutrons: 104, electrons: 71, mass: 174.97, meltingPointC: 1663, boilingPointC: 3402, stateAt20C: "fest", techApplications: ["Elektrotechnik: LSO-Detektoren in PET-Scannern", "Petrolchemie-Katalysatoren", "Hochbrechende Linsen"], compounds: ["Lu₂O₃", "LuCl₃"]),
        Element(z: 72, symbol: "Hf", col: 4, row: 6, category: .transition, nameDE: "Hafnium", nameFR: "Hafnium", nameEN: "Hafnium", nameLA: "Hafnium", protons: 72, neutrons: 106, electrons: 72, mass: 178.49, meltingPointC: 2233, boilingPointC: 4603, stateAt20C: "fest", techApplications: ["Elektrotechnik: HfO₂ als High-k-Dielektrikum in modernen CPUs (ab 45 nm)", "Steuerstäbe in Atom-U-Booten", "Plasmaschneider-Elektroden"], compounds: ["HfO₂", "HfCl₄"]),
        Element(z: 73, symbol: "Ta", col: 5, row: 6, category: .transition, nameDE: "Tantal", nameFR: "Tantale", nameEN: "Tantalum", nameLA: "Tantalum", protons: 73, neutrons: 108, electrons: 73, mass: 180.95, meltingPointC: 3017, boilingPointC: 5458, stateAt20C: "fest", techApplications: ["Elektrotechnik: Tantalkondensatoren in Smartphones, Laptops, Medizingeräten (hohe Kapazitätsdichte)", "Hochtemperatur-Legierungen", "Implantate"], compounds: ["Ta₂O₅", "TaC"]),
        Element(z: 74, symbol: "W", col: 6, row: 6, category: .transition, nameDE: "Wolfram", nameFR: "Tungstène", nameEN: "Tungsten", nameLA: "Wolframium", protons: 74, neutrons: 110, electrons: 74, mass: 183.84, meltingPointC: 3422, boilingPointC: 5555, stateAt20C: "fest", techApplications: ["Elektrotechnik: Glühwendel in Glühlampen & Halogenlampen", "Elektroden beim WIG-Schweißen & in Röntgenröhren", "Hartmetall (WC) für Werkzeuge", "Kontakte"], compounds: ["WO₃", "WC (Wolframcarbid)", "WS₂"]),
        Element(z: 75, symbol: "Re", col: 7, row: 6, category: .transition, nameDE: "Rhenium", nameFR: "Rhénium", nameEN: "Rhenium", nameLA: "Rhenium", protons: 75, neutrons: 111, electrons: 75, mass: 186.21, meltingPointC: 3186, boilingPointC: 5596, stateAt20C: "fest", techApplications: ["Elektrotechnik: Hochtemperatur-Thermoelemente (Pt-Re, W-Re)", "Massenspektrometer-Filamente", "Turbinenschaufeln"], compounds: ["Re₂O₇", "ReCl₃", "ReS₂"]),
        Element(z: 76, symbol: "Os", col: 8, row: 6, category: .transition, nameDE: "Osmium", nameFR: "Osmium", nameEN: "Osmium", nameLA: "Osmium", protons: 76, neutrons: 114, electrons: 76, mass: 190.23, meltingPointC: 3033, boilingPointC: 5012, stateAt20C: "fest", techApplications: ["Elektrotechnik: Spitzen für Plattenspieler-Nadeln & Federspitzen", "Elektrische Kontakte (sehr hart)", "Katalysatoren"], compounds: ["OsO₄", "OsCl₃"]),
        Element(z: 77, symbol: "Ir", col: 9, row: 6, category: .transition, nameDE: "Iridium", nameFR: "Iridium", nameEN: "Iridium", nameLA: "Iridium", protons: 77, neutrons: 115, electrons: 77, mass: 192.22, meltingPointC: 2466, boilingPointC: 4428, stateAt20C: "fest", techApplications: ["Elektrotechnik: Zündkerzenelektroden (Hochleistung)", "OLED-Emittermaterialien", "Tiegel für Einkristallzucht (LED-Wafer)"], compounds: ["IrO₂", "IrCl₃"]),
        Element(z: 78, symbol: "Pt", col: 10, row: 6, category: .transition, nameDE: "Platin", nameFR: "Platine", nameEN: "Platinum", nameLA: "Platinum", protons: 78, neutrons: 117, electrons: 78, mass: 195.08, meltingPointC: 1768.3, boilingPointC: 3825, stateAt20C: "fest", techApplications: ["Elektrotechnik: Pt100-Widerstandsthermometer (Industriestandard)", "Brennstoffzellen-Elektroden", "Festplatten-Beschichtungen", "Kfz-Katalysatoren", "Schmuck"], compounds: ["PtO₂", "PtCl₂", "PtCl₄"]),
        Element(z: 79, symbol: "Au", col: 11, row: 6, category: .transition, nameDE: "Gold", nameFR: "Or", nameEN: "Gold", nameLA: "Aurum", protons: 79, neutrons: 118, electrons: 79, mass: 196.97, meltingPointC: 1064.18, boilingPointC: 2856, stateAt20C: "fest", techApplications: ["Elektrotechnik: Bonddrähte in ICs, vergoldete Steckkontakte (USB, HDMI, Stecker)", "Leiterbahnen in Hochzuverlässigkeitselektronik", "IR-Reflexion in Raumfahrt", "Schmuck, Münzen"], compounds: ["AuCl₃", "Au₂O₃", "HAuCl₄"]),
        Element(z: 80, symbol: "Hg", col: 12, row: 6, category: .transition, nameDE: "Quecksilber", nameFR: "Mercure", nameEN: "Mercury", nameLA: "Hydrargyrum", protons: 80, neutrons: 121, electrons: 80, mass: 200.59, meltingPointC: -38.83, boilingPointC: 356.73, stateAt20C: "flüssig", techApplications: ["Elektrotechnik: Quecksilberdampflampen, Leuchtstoffröhren, Energiesparlampen", "Quecksilberschalter (heute verboten)", "Thermometer (RoHS-beschränkt)"], compounds: ["HgO", "HgCl₂", "HgS (Zinnober)"]),
        Element(z: 81, symbol: "Tl", col: 13, row: 6, category: .posttransition, nameDE: "Thallium", nameFR: "Thallium", nameEN: "Thallium", nameLA: "Thallium", protons: 81, neutrons: 123, electrons: 81, mass: 204.38, meltingPointC: 304, boilingPointC: 1473, stateAt20C: "fest", techApplications: ["Elektrotechnik: Infrarot-Detektoren (Tl-Verbindungen)", "Hochtemperatur-Supraleiter (TBCCO)", "Photozellen", "Optische Linsen für IR"], compounds: ["Tl₂O", "TlCl", "Tl₂SO₄"]),
        Element(z: 82, symbol: "Pb", col: 14, row: 6, category: .posttransition, nameDE: "Blei", nameFR: "Plomb", nameEN: "Lead", nameLA: "Plumbum", protons: 82, neutrons: 125, electrons: 82, mass: 207.2, meltingPointC: 327.46, boilingPointC: 1749, stateAt20C: "fest", techApplications: ["Elektrotechnik: Bleiakkumulatoren (Starterbatterien Kfz, USV)", "Strahlenschirmung (Röntgen, Reaktoren)", "Lote (heute meist bleifrei)", "Kabelmäntel (historisch)"], compounds: ["PbO", "PbO₂", "PbS", "PbSO₄", "Pb(NO₃)₂"]),
        Element(z: 83, symbol: "Bi", col: 15, row: 6, category: .posttransition, nameDE: "Bismut", nameFR: "Bismuth", nameEN: "Bismuth", nameLA: "Bisemutum", protons: 83, neutrons: 126, electrons: 83, mass: 208.98, meltingPointC: 271.4, boilingPointC: 1564, stateAt20C: "fest", techApplications: ["Elektrotechnik: Bi-haltige bleifreie Lote", "Bi₂Te₃ in thermoelektrischen Generatoren & Peltier-Elementen", "Hochtemperatur-Supraleiter (BSCCO)", "Pharmazie"], compounds: ["Bi₂O₃", "BiOCl", "Bi₂Te₃", "Bi₂S₃"]),
        Element(z: 84, symbol: "Po", col: 16, row: 6, category: .metalloid, nameDE: "Polonium", nameFR: "Polonium", nameEN: "Polonium", nameLA: "Polonium", protons: 84, neutrons: 125, electrons: 84, mass: 209.0, meltingPointC: 254, boilingPointC: 962, stateAt20C: "fest", techApplications: ["Elektrotechnik: Antistatik-Bürsten (α-Strahler ionisiert Luft)", "Wärmequelle in Satelliten-RTGs", "Neutronenquellen"], compounds: ["PoO₂", "PoCl₂"]),
        Element(z: 85, symbol: "At", col: 17, row: 6, category: .halogen, nameDE: "Astat", nameFR: "Astate", nameEN: "Astatine", nameLA: "Astatum", protons: 85, neutrons: 125, electrons: 85, mass: 210.0, meltingPointC: 302, boilingPointC: 337, stateAt20C: "fest", techApplications: ["Elektrotechnik: praktisch keine Anwendung (extrem selten, radioaktiv)", "Forschung: zielgerichtete Krebstherapie (²¹¹At)"], compounds: ["HAt (instabil)", "AtI"]),
        Element(z: 86, symbol: "Rn", col: 18, row: 6, category: .noblegas, nameDE: "Radon", nameFR: "Radon", nameEN: "Radon", nameLA: "Radon", protons: 86, neutrons: 136, electrons: 86, mass: 222.0, meltingPointC: -71, boilingPointC: -61.7, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: keine technische Nutzung", "Strahlentherapie (historisch)", "Indikator für tektonische Aktivität"], compounds: ["RnF₂"]),
        Element(z: 87, symbol: "Fr", col: 1, row: 7, category: .alkali, nameDE: "Francium", nameFR: "Francium", nameEN: "Francium", nameLA: "Francium", protons: 87, neutrons: 136, electrons: 87, mass: 223.0, meltingPointC: 27, boilingPointC: 677, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine (extrem selten, radioaktiv)", "Nur Forschung (atomare Struktur)"], compounds: ["FrCl", "Fr₂O"]),
        Element(z: 88, symbol: "Ra", col: 2, row: 7, category: .alkaline, nameDE: "Radium", nameFR: "Radium", nameEN: "Radium", nameLA: "Radium", protons: 88, neutrons: 138, electrons: 88, mass: 226.0, meltingPointC: 700, boilingPointC: 1737, stateAt20C: "fest", techApplications: ["Elektrotechnik: Leuchtfarben für Zifferblätter (historisch, heute verboten)", "Bestrahlungsquellen (Medizin, historisch)"], compounds: ["RaCl₂", "RaSO₄", "RaBr₂"]),
        Element(z: 89, symbol: "Ac", col: 3, row: 7, category: .actinide, nameDE: "Actinium", nameFR: "Actinium", nameEN: "Actinium", nameLA: "Actinium", protons: 89, neutrons: 138, electrons: 89, mass: 227.0, meltingPointC: 1050, boilingPointC: 3200, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine technische Nutzung", "Neutronenquelle (Ac-Be)", "Krebstherapie (²²⁵Ac, gezielte Alphatherapie)"], compounds: ["Ac₂O₃", "AcCl₃"]),
        Element(z: 90, symbol: "Th", col: 4, row: 7, category: .actinide, nameDE: "Thorium", nameFR: "Thorium", nameEN: "Thorium", nameLA: "Thorium", protons: 90, neutrons: 142, electrons: 90, mass: 232.04, meltingPointC: 1750, boilingPointC: 4788, stateAt20C: "fest", techApplications: ["Elektrotechnik: Glühstrümpfe (historisch)", "WIG-Schweißelektroden (thoriert, ersetzt durch CeO₂)", "Brennstoff in zukünftigen Thorium-Reaktoren", "Hochtemperatur-Optik"], compounds: ["ThO₂", "ThF₄", "ThCl₄"]),
    ]
}
