// AUTO-GENERATED. Do not edit by hand.
// Quelle: index.html (Tom BLEYER, 05/2026)

import Foundation

extension ElementsData {
    static let part_91_118: [Element] = [
        Element(z: 91, symbol: "Pa", col: 5, row: 7, category: .actinide, nameDE: "Protactinium", nameFR: "Protactinium", nameEN: "Protactinium", nameLA: "Protactinium", protons: 91, neutrons: 140, electrons: 91, mass: 231.04, meltingPointC: 1568, boilingPointC: 4027, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine", "Forschung: Zwischenstufe in Thorium-Brutreaktoren"], compounds: ["Pa₂O₅", "PaF₅"]),
        Element(z: 92, symbol: "U", col: 6, row: 7, category: .actinide, nameDE: "Uran", nameFR: "Uranium", nameEN: "Uranium", nameLA: "Uranium", protons: 92, neutrons: 146, electrons: 92, mass: 238.03, meltingPointC: 1132.2, boilingPointC: 4131, stateAt20C: "fest", techApplications: ["Elektrotechnik: Brennstoff in Kernkraftwerken (Stromerzeugung)", "Glasfärbung (Uranglas)", "Wuchtgewichte (DU)", "Atomwaffen"], compounds: ["UO₂", "UF₆", "U₃O₈", "UCl₄"]),
        Element(z: 93, symbol: "Np", col: 7, row: 7, category: .actinide, nameDE: "Neptunium", nameFR: "Neptunium", nameEN: "Neptunium", nameLA: "Neptunium", protons: 93, neutrons: 144, electrons: 93, mass: 237.0, meltingPointC: 644, boilingPointC: 3902, stateAt20C: "fest", techApplications: ["Elektrotechnik: Neutronendetektoren", "Plutonium-Vorläufer in Reaktoren"], compounds: ["NpO₂", "NpF₆"]),
        Element(z: 94, symbol: "Pu", col: 8, row: 7, category: .actinide, nameDE: "Plutonium", nameFR: "Plutonium", nameEN: "Plutonium", nameLA: "Plutonium", protons: 94, neutrons: 150, electrons: 94, mass: 244.0, meltingPointC: 639.4, boilingPointC: 3228, stateAt20C: "fest", techApplications: ["Elektrotechnik: RTGs (Radioisotopengeneratoren) für Raumsonden (Voyager, Curiosity)", "Brennstoff in Schnellen Brutreaktoren", "Atomwaffen"], compounds: ["PuO₂", "PuF₆", "PuCl₃"]),
        Element(z: 95, symbol: "Am", col: 9, row: 7, category: .actinide, nameDE: "Americium", nameFR: "Américium", nameEN: "Americium", nameLA: "Americium", protons: 95, neutrons: 148, electrons: 95, mass: 243.0, meltingPointC: 1176, boilingPointC: 2011, stateAt20C: "fest", techApplications: ["Elektrotechnik: ²⁴¹Am in Ionisationsrauchmeldern (am häufigsten genutzt!)", "Industriedickenmessgeräte"], compounds: ["AmO₂", "AmCl₃"]),
        Element(z: 96, symbol: "Cm", col: 10, row: 7, category: .actinide, nameDE: "Curium", nameFR: "Curium", nameEN: "Curium", nameLA: "Curium", protons: 96, neutrons: 151, electrons: 96, mass: 247.0, meltingPointC: 1340, boilingPointC: 3110, stateAt20C: "fest", techApplications: ["Elektrotechnik: α-Quelle für Röntgenfluoreszenz-Spektrometer (z.B. Mars-Rover APXS)", "RTG-Forschung"], compounds: ["CmO₂", "CmCl₃"]),
        Element(z: 97, symbol: "Bk", col: 11, row: 7, category: .actinide, nameDE: "Berkelium", nameFR: "Berkélium", nameEN: "Berkelium", nameLA: "Berkelium", protons: 97, neutrons: 150, electrons: 97, mass: 247.0, meltingPointC: 986, boilingPointC: 2627, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine", "Forschung: Synthese schwererer Elemente (Tennessine)"], compounds: ["BkO₂", "BkCl₃"]),
        Element(z: 98, symbol: "Cf", col: 12, row: 7, category: .actinide, nameDE: "Californium", nameFR: "Californium", nameEN: "Californium", nameLA: "Californium", protons: 98, neutrons: 153, electrons: 98, mass: 251.0, meltingPointC: 900, boilingPointC: 1745, stateAt20C: "fest", techApplications: ["Elektrotechnik: ²⁵²Cf als Neutronenquelle (Reaktor-Startup, Bohrlochmessungen, Krebstherapie)"], compounds: ["CfO₂", "CfCl₃"]),
        Element(z: 99, symbol: "Es", col: 13, row: 7, category: .actinide, nameDE: "Einsteinium", nameFR: "Einsteinium", nameEN: "Einsteinium", nameLA: "Einsteinium", protons: 99, neutrons: 153, electrons: 99, mass: 252.0, meltingPointC: 860, boilingPointC: 996, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine", "Reine Grundlagenforschung"], compounds: ["Es₂O₃", "EsCl₃"]),
        Element(z: 100, symbol: "Fm", col: 14, row: 7, category: .actinide, nameDE: "Fermium", nameFR: "Fermium", nameEN: "Fermium", nameLA: "Fermium", protons: 100, neutrons: 157, electrons: 100, mass: 257.0, meltingPointC: 1527, boilingPointC: nil, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine", "Reine Grundlagenforschung"], compounds: ["FmCl₂"]),
        Element(z: 101, symbol: "Md", col: 15, row: 7, category: .actinide, nameDE: "Mendelevium", nameFR: "Mendélévium", nameEN: "Mendelevium", nameLA: "Mendelevium", protons: 101, neutrons: 157, electrons: 101, mass: 258.0, meltingPointC: 827, boilingPointC: nil, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine", "Reine Grundlagenforschung"], compounds: ["MdCl₃"]),
        Element(z: 102, symbol: "No", col: 16, row: 7, category: .actinide, nameDE: "Nobelium", nameFR: "Nobélium", nameEN: "Nobelium", nameLA: "Nobelium", protons: 102, neutrons: 157, electrons: 102, mass: 259.0, meltingPointC: 827, boilingPointC: nil, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine", "Reine Grundlagenforschung"], compounds: ["NoCl₂"]),
        Element(z: 103, symbol: "Lr", col: 17, row: 7, category: .actinide, nameDE: "Lawrencium", nameFR: "Lawrencium", nameEN: "Lawrencium", nameLA: "Lawrencium", protons: 103, neutrons: 159, electrons: 103, mass: 266.0, meltingPointC: 1627, boilingPointC: nil, stateAt20C: "fest", techApplications: ["Elektrotechnik: keine", "Reine Grundlagenforschung"], compounds: ["LrCl₃"]),
        Element(z: 104, symbol: "Rf", col: 4, row: 7, category: .transition, nameDE: "Rutherfordium", nameFR: "Rutherfordium", nameEN: "Rutherfordium", nameLA: "Rutherfordium", protons: 104, neutrons: 163, electrons: 104, mass: 267.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "fest (vermutet)", techApplications: ["Elektrotechnik: keine (extrem instabil)", "Grundlagenforschung"], compounds: ["RfCl₄ (vermutet)"]),
        Element(z: 105, symbol: "Db", col: 5, row: 7, category: .transition, nameDE: "Dubnium", nameFR: "Dubnium", nameEN: "Dubnium", nameLA: "Dubnium", protons: 105, neutrons: 163, electrons: 105, mass: 268.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "fest (vermutet)", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["DbCl₅ (vermutet)"]),
        Element(z: 106, symbol: "Sg", col: 6, row: 7, category: .transition, nameDE: "Seaborgium", nameFR: "Seaborgium", nameEN: "Seaborgium", nameLA: "Seaborgium", protons: 106, neutrons: 163, electrons: 106, mass: 269.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "fest (vermutet)", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["SgO₃ (vermutet)"]),
        Element(z: 107, symbol: "Bh", col: 7, row: 7, category: .transition, nameDE: "Bohrium", nameFR: "Bohrium", nameEN: "Bohrium", nameLA: "Bohrium", protons: 107, neutrons: 163, electrons: 107, mass: 270.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "fest (vermutet)", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["BhO₃Cl (vermutet)"]),
        Element(z: 108, symbol: "Hs", col: 8, row: 7, category: .transition, nameDE: "Hassium", nameFR: "Hassium", nameEN: "Hassium", nameLA: "Hassium", protons: 108, neutrons: 169, electrons: 108, mass: 269.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "fest (vermutet)", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["HsO₄ (vermutet)"]),
        Element(z: 109, symbol: "Mt", col: 9, row: 7, category: .unknown, nameDE: "Meitnerium", nameFR: "Meitnérium", nameEN: "Meitnerium", nameLA: "Meitnerium", protons: 109, neutrons: 169, electrons: 109, mass: 278.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 110, symbol: "Ds", col: 10, row: 7, category: .unknown, nameDE: "Darmstadtium", nameFR: "Darmstadtium", nameEN: "Darmstadtium", nameLA: "Darmstadtium", protons: 110, neutrons: 171, electrons: 110, mass: 281.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 111, symbol: "Rg", col: 11, row: 7, category: .unknown, nameDE: "Roentgenium", nameFR: "Roentgenium", nameEN: "Roentgenium", nameLA: "Roentgenium", protons: 111, neutrons: 171, electrons: 111, mass: 282.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 112, symbol: "Cn", col: 12, row: 7, category: .unknown, nameDE: "Copernicium", nameFR: "Copernicium", nameEN: "Copernicium", nameLA: "Copernicium", protons: 112, neutrons: 173, electrons: 112, mass: 285.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "vermutlich flüssig", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 113, symbol: "Nh", col: 13, row: 7, category: .unknown, nameDE: "Nihonium", nameFR: "Nihonium", nameEN: "Nihonium", nameLA: "Nihonium", protons: 113, neutrons: 173, electrons: 113, mass: 286.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 114, symbol: "Fl", col: 14, row: 7, category: .unknown, nameDE: "Flerovium", nameFR: "Flérovium", nameEN: "Flerovium", nameLA: "Flerovium", protons: 114, neutrons: 175, electrons: 114, mass: 289.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 115, symbol: "Mc", col: 15, row: 7, category: .unknown, nameDE: "Moscovium", nameFR: "Moscovium", nameEN: "Moscovium", nameLA: "Moscovium", protons: 115, neutrons: 175, electrons: 115, mass: 289.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 116, symbol: "Lv", col: 16, row: 7, category: .unknown, nameDE: "Livermorium", nameFR: "Livermorium", nameEN: "Livermorium", nameLA: "Livermorium", protons: 116, neutrons: 177, electrons: 116, mass: 293.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 117, symbol: "Ts", col: 17, row: 7, category: .unknown, nameDE: "Tenness", nameFR: "Tennesse", nameEN: "Tennessine", nameLA: "Tennessium", protons: 117, neutrons: 177, electrons: 117, mass: 294.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
        Element(z: 118, symbol: "Og", col: 18, row: 7, category: .unknown, nameDE: "Oganesson", nameFR: "Oganesson", nameEN: "Oganesson", nameLA: "Oganesson", protons: 118, neutrons: 176, electrons: 118, mass: 294.0, meltingPointC: nil, boilingPointC: nil, stateAt20C: "unbekannt", techApplications: ["Elektrotechnik: keine", "Grundlagenforschung"], compounds: ["unbekannt"]),
    ]
}
