// AUTO-GENERATED. Do not edit by hand.
// Quelle: index.html (Tom BLEYER, 05/2026)

import Foundation

extension ElementsData {
    static let part_1_30: [Element] = [
        Element(z: 1, symbol: "H", col: 1, row: 1, category: .nonmetal, nameDE: "Wasserstoff", nameFR: "Hydrogène", nameEN: "Hydrogen", nameLA: "Hydrogenium", protons: 1, neutrons: 0, electrons: 1, mass: 1.008, meltingPointC: -259.16, boilingPointC: -252.87, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: Brennstoffzellen für Elektrofahrzeuge & stationäre Stromversorgung", "Kühlmittel in Großgeneratoren", "Energieträger (Power-to-Gas)", "Reduktionsmittel in der Halbleiterfertigung", "Schweißgas (atomares Wasserstoffschweißen)"], compounds: ["H₂O (Wasser)", "HCl (Salzsäure)", "NH₃ (Ammoniak)", "CH₄ (Methan)", "H₂SO₄ (Schwefelsäure)"]),
        Element(z: 2, symbol: "He", col: 18, row: 1, category: .noblegas, nameDE: "Helium", nameFR: "Hélium", nameEN: "Helium", nameLA: "Helium", protons: 2, neutrons: 2, electrons: 2, mass: 4.0026, meltingPointC: -272.2, boilingPointC: -268.93, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: Kühlung supraleitender Magnete (MRT, Teilchenbeschleuniger)", "Schutzgas beim Lichtbogenschweißen", "Lecksuche in Vakuumanlagen", "Trägergas in der Gaschromatografie"], compounds: ["Keine stabilen Verbindungen (Edelgas)", "HeH⁺ (nur unter extremen Bedingungen)"]),
        Element(z: 3, symbol: "Li", col: 1, row: 2, category: .alkali, nameDE: "Lithium", nameFR: "Lithium", nameEN: "Lithium", nameLA: "Lithium", protons: 3, neutrons: 4, electrons: 3, mass: 6.94, meltingPointC: 180.5, boilingPointC: 1342, stateAt20C: "fest", techApplications: ["Elektrotechnik: Lithium-Ionen-Akkus (Smartphones, E-Autos, Powerbanks)", "Lithium-Polymer-Akkus", "Schmiermittel (Lithiumseifen)", "Glas- und Keramikherstellung"], compounds: ["LiOH (Lithiumhydroxid)", "Li₂CO₃ (Lithiumcarbonat)", "LiCl (Lithiumchlorid)", "LiF (Lithiumfluorid)"]),
        Element(z: 4, symbol: "Be", col: 2, row: 2, category: .alkaline, nameDE: "Beryllium", nameFR: "Béryllium", nameEN: "Beryllium", nameLA: "Beryllium", protons: 4, neutrons: 5, electrons: 4, mass: 9.0122, meltingPointC: 1287, boilingPointC: 2469, stateAt20C: "fest", techApplications: ["Elektrotechnik: Berylliumkupfer in Federkontakten und Steckverbindern (nicht funkend)", "Röntgenfenster", "Strukturteile in Luft- & Raumfahrt", "Reflektor in Kernreaktoren"], compounds: ["BeO (Berylliumoxid)", "BeF₂ (Berylliumfluorid)", "Be(OH)₂"]),
        Element(z: 5, symbol: "B", col: 13, row: 2, category: .metalloid, nameDE: "Bor", nameFR: "Bore", nameEN: "Boron", nameLA: "Borium", protons: 5, neutrons: 6, electrons: 5, mass: 10.81, meltingPointC: 2076, boilingPointC: 3927, stateAt20C: "fest", techApplications: ["Elektrotechnik: Dotierung von Silizium (p-Halbleiter)", "Bornitrid als Isolator in Hochleistungselektronik", "Borsilikatglas (Laborgeräte)", "Verstärkung in Verbundwerkstoffen"], compounds: ["H₃BO₃ (Borsäure)", "Na₂B₄O₇ (Borax)", "BN (Bornitrid)", "B₂O₃"]),
        Element(z: 6, symbol: "C", col: 14, row: 2, category: .nonmetal, nameDE: "Kohlenstoff", nameFR: "Carbone", nameEN: "Carbon", nameLA: "Carbonium", protons: 6, neutrons: 6, electrons: 6, mass: 12.011, meltingPointC: 3550, boilingPointC: 4827, stateAt20C: "fest", techApplications: ["Elektrotechnik: Graphitelektroden, Kohlebürsten in Motoren", "Carbon Nanotubes & Graphen für Halbleiter", "Aktivkohle-Filter", "Diamantbeschichtung für Werkzeuge", "CFK-Verbundwerkstoffe"], compounds: ["CO₂ (Kohlendioxid)", "CH₄ (Methan)", "CaCO₃ (Calciumcarbonat)", "C₆H₁₂O₆ (Glucose)"]),
        Element(z: 7, symbol: "N", col: 15, row: 2, category: .nonmetal, nameDE: "Stickstoff", nameFR: "Azote", nameEN: "Nitrogen", nameLA: "Nitrogenium", protons: 7, neutrons: 7, electrons: 7, mass: 14.007, meltingPointC: -210, boilingPointC: -195.79, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: Schutzgas in Lötanlagen (SMD-Reflow)", "Kühlmittel (flüssig) für Sensoren", "Inertgas in Halbleiterfertigung", "Reifenfüllung", "Lebensmittelverpackung"], compounds: ["NH₃ (Ammoniak)", "HNO₃ (Salpetersäure)", "NO₂ (Stickstoffdioxid)", "N₂O (Lachgas)"]),
        Element(z: 8, symbol: "O", col: 16, row: 2, category: .nonmetal, nameDE: "Sauerstoff", nameFR: "Oxygène", nameEN: "Oxygen", nameLA: "Oxygenium", protons: 8, neutrons: 8, electrons: 8, mass: 15.999, meltingPointC: -218.79, boilingPointC: -182.95, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: Oxidation in Halbleiterfertigung (SiO₂-Schichten)", "Brenngas beim Schweißen/Schneiden", "Stahlerzeugung", "Medizinische Beatmung"], compounds: ["H₂O (Wasser)", "CO₂", "Fe₂O₃ (Rost)", "SO₃", "O₃ (Ozon)"]),
        Element(z: 9, symbol: "F", col: 17, row: 2, category: .halogen, nameDE: "Fluor", nameFR: "Fluor", nameEN: "Fluorine", nameLA: "Fluorum", protons: 9, neutrons: 10, electrons: 9, mass: 18.998, meltingPointC: -219.67, boilingPointC: -188.11, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: SF₆ als Isoliergas in Hochspannungsschaltanlagen", "Ätzgase in Halbleiterfertigung (z.B. CF₄)", "PTFE (Teflon) als Isolator", "Lithiumbatterien"], compounds: ["HF (Flusssäure)", "NaF", "CaF₂ (Flussspat)", "SF₆", "Teflon (PTFE)"]),
        Element(z: 10, symbol: "Ne", col: 18, row: 2, category: .noblegas, nameDE: "Neon", nameFR: "Néon", nameEN: "Neon", nameLA: "Neon", protons: 10, neutrons: 10, electrons: 10, mass: 20.18, meltingPointC: -248.59, boilingPointC: -246.05, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: Neonröhren (Leuchtreklamen, Anzeigen)", "Glimmlampen", "Hochspannungsanzeiger", "Helium-Neon-Laser"], compounds: ["Keine stabilen Verbindungen (Edelgas)"]),
        Element(z: 11, symbol: "Na", col: 1, row: 3, category: .alkali, nameDE: "Natrium", nameFR: "Sodium", nameEN: "Sodium", nameLA: "Natrium", protons: 11, neutrons: 12, electrons: 11, mass: 22.99, meltingPointC: 97.79, boilingPointC: 883, stateAt20C: "fest", techApplications: ["Elektrotechnik: Natriumdampflampen (Straßenbeleuchtung)", "Natrium-Schwefel-Akkus (stationäre Speicher)", "Kühlmittel in schnellen Brutreaktoren"], compounds: ["NaCl (Kochsalz)", "NaOH (Natronlauge)", "Na₂CO₃ (Soda)", "NaHCO₃ (Natron)"]),
        Element(z: 12, symbol: "Mg", col: 2, row: 3, category: .alkaline, nameDE: "Magnesium", nameFR: "Magnésium", nameEN: "Magnesium", nameLA: "Magnesium", protons: 12, neutrons: 12, electrons: 12, mass: 24.305, meltingPointC: 650, boilingPointC: 1090, stateAt20C: "fest", techApplications: ["Elektrotechnik: Gehäuse für Laptops & Smartphones (leicht, abschirmend)", "Anode in Galvanik-Zellen", "Leichtbau in Fahrzeugen", "Pyrotechnik"], compounds: ["MgO (Magnesia)", "MgCl₂", "Mg(OH)₂", "MgSO₄ (Bittersalz)"]),
        Element(z: 13, symbol: "Al", col: 13, row: 3, category: .posttransition, nameDE: "Aluminium", nameFR: "Aluminium", nameEN: "Aluminium", nameLA: "Aluminium", protons: 13, neutrons: 14, electrons: 13, mass: 26.982, meltingPointC: 660.32, boilingPointC: 2470, stateAt20C: "fest", techApplications: ["Elektrotechnik: Hochspannungs-Freileitungen (leicht, leitfähig)", "Kondensatoren (Elektrolytkondensatoren)", "Kühlkörper", "Leiterplatten-Substrate", "Karosserie & Verpackungen"], compounds: ["Al₂O₃ (Korund)", "AlCl₃", "Al(OH)₃", "KAl(SO₄)₂ (Alaun)"]),
        Element(z: 14, symbol: "Si", col: 14, row: 3, category: .metalloid, nameDE: "Silicium", nameFR: "Silicium", nameEN: "Silicon", nameLA: "Silicium", protons: 14, neutrons: 14, electrons: 14, mass: 28.085, meltingPointC: 1414, boilingPointC: 3265, stateAt20C: "fest", techApplications: ["Elektrotechnik: BASIS aller Halbleiter & Mikrochips (CPUs, Speicher)", "Solarzellen (Photovoltaik)", "MOSFETs, Dioden, Transistoren", "Silikon-Dichtmasse", "Glas- und Keramikherstellung"], compounds: ["SiO₂ (Quarz)", "SiC (Siliciumcarbid)", "Si₃N₄", "H₂SiO₃", "Silikate"]),
        Element(z: 15, symbol: "P", col: 15, row: 3, category: .nonmetal, nameDE: "Phosphor", nameFR: "Phosphore", nameEN: "Phosphorus", nameLA: "Phosphorus", protons: 15, neutrons: 16, electrons: 15, mass: 30.974, meltingPointC: 44.15, boilingPointC: 280.5, stateAt20C: "fest", techApplications: ["Elektrotechnik: Dotierung von Silizium (n-Halbleiter)", "LED-Leuchtstoffe", "Streichhölzer", "Düngemittel", "Brandhemmer in Kunststoffen"], compounds: ["H₃PO₄ (Phosphorsäure)", "P₂O₅", "Ca₃(PO₄)₂", "PCl₃"]),
        Element(z: 16, symbol: "S", col: 16, row: 3, category: .nonmetal, nameDE: "Schwefel", nameFR: "Soufre", nameEN: "Sulfur", nameLA: "Sulfur", protons: 16, neutrons: 16, electrons: 16, mass: 32.06, meltingPointC: 115.21, boilingPointC: 444.6, stateAt20C: "fest", techApplications: ["Elektrotechnik: Lithium-Schwefel-Batterien (Hochenergie)", "Vulkanisation von Gummi (Kabelisolation)", "Schwefelsäure-Akkus (Bleiakku-Elektrolyt)"], compounds: ["H₂SO₄ (Schwefelsäure)", "SO₂", "H₂S", "FeS₂ (Pyrit)", "CaSO₄ (Gips)"]),
        Element(z: 17, symbol: "Cl", col: 17, row: 3, category: .halogen, nameDE: "Chlor", nameFR: "Chlore", nameEN: "Chlorine", nameLA: "Chlorum", protons: 17, neutrons: 18, electrons: 17, mass: 35.45, meltingPointC: -101.5, boilingPointC: -34.04, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: PVC-Kabelisolierung", "Chloralkali-Elektrolyse", "Wasserdesinfektion", "Bleichmittel"], compounds: ["NaCl", "HCl (Salzsäure)", "PVC", "KCl", "CaCl₂"]),
        Element(z: 18, symbol: "Ar", col: 18, row: 3, category: .noblegas, nameDE: "Argon", nameFR: "Argon", nameEN: "Argon", nameLA: "Argon", protons: 18, neutrons: 22, electrons: 18, mass: 39.948, meltingPointC: -189.34, boilingPointC: -185.85, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: Schutzgas in Glühbirnen & Leuchtstoffröhren", "Schutzgas beim WIG-Schweißen", "Plasmagas in Halbleiterfertigung", "Wärmedämmung in Isolierglas"], compounds: ["Keine stabilen Verbindungen (Edelgas)", "HArF (extreme Bedingungen)"]),
        Element(z: 19, symbol: "K", col: 1, row: 4, category: .alkali, nameDE: "Kalium", nameFR: "Potassium", nameEN: "Potassium", nameLA: "Kalium", protons: 19, neutrons: 20, electrons: 19, mass: 39.098, meltingPointC: 63.5, boilingPointC: 759, stateAt20C: "fest", techApplications: ["Elektrotechnik: Kalium-Ionen-Batterien (Forschung)", "Photoelektrische Zellen", "Düngemittel", "Glasherstellung"], compounds: ["KCl", "KOH (Kalilauge)", "K₂CO₃ (Pottasche)", "KNO₃ (Salpeter)"]),
        Element(z: 20, symbol: "Ca", col: 2, row: 4, category: .alkaline, nameDE: "Calcium", nameFR: "Calcium", nameEN: "Calcium", nameLA: "Calcium", protons: 20, neutrons: 20, electrons: 20, mass: 40.078, meltingPointC: 842, boilingPointC: 1484, stateAt20C: "fest", techApplications: ["Elektrotechnik: Reduktionsmittel bei Metallgewinnung", "Elektroden in einigen Batterien", "Bauwesen (Zement, Mörtel)", "Stahlentschwefelung"], compounds: ["CaCO₃ (Kalk)", "CaO (Branntkalk)", "Ca(OH)₂", "CaSO₄ (Gips)", "CaCl₂"]),
        Element(z: 21, symbol: "Sc", col: 3, row: 4, category: .transition, nameDE: "Scandium", nameFR: "Scandium", nameEN: "Scandium", nameLA: "Scandium", protons: 21, neutrons: 24, electrons: 21, mass: 44.956, meltingPointC: 1541, boilingPointC: 2836, stateAt20C: "fest", techApplications: ["Elektrotechnik: Scandium-Aluminium-Legierung in Antennen & Hochspannungstechnik", "Quecksilberdampflampen (Sportstadien)", "Luft- & Raumfahrt-Legierungen"], compounds: ["Sc₂O₃", "ScCl₃", "ScF₃"]),
        Element(z: 22, symbol: "Ti", col: 4, row: 4, category: .transition, nameDE: "Titan", nameFR: "Titane", nameEN: "Titanium", nameLA: "Titanium", protons: 22, neutrons: 26, electrons: 22, mass: 47.867, meltingPointC: 1668, boilingPointC: 3287, stateAt20C: "fest", techApplications: ["Elektrotechnik: Kondensatoren (TiO₂-Dielektrika)", "Anoden in MMO-Elektroden", "Implantate, Flugzeugbau", "Weißpigment in Lacken"], compounds: ["TiO₂ (Titandioxid)", "TiCl₄", "TiN (Titannitrid)"]),
        Element(z: 23, symbol: "V", col: 5, row: 4, category: .transition, nameDE: "Vanadium", nameFR: "Vanadium", nameEN: "Vanadium", nameLA: "Vanadium", protons: 23, neutrons: 28, electrons: 23, mass: 50.942, meltingPointC: 1910, boilingPointC: 3407, stateAt20C: "fest", techApplications: ["Elektrotechnik: Vanadium-Redox-Flow-Batterien (Großspeicher)", "Hochfeste Stahllegierungen", "Katalysator (Schwefelsäure)", "Supraleitung (V₃Ga)"], compounds: ["V₂O₅", "VO₂", "VCl₃"]),
        Element(z: 24, symbol: "Cr", col: 6, row: 4, category: .transition, nameDE: "Chrom", nameFR: "Chrome", nameEN: "Chromium", nameLA: "Chromium", protons: 24, neutrons: 28, electrons: 24, mass: 51.996, meltingPointC: 1907, boilingPointC: 2671, stateAt20C: "fest", techApplications: ["Elektrotechnik: Verchromung von Kontakten (Korrosionsschutz)", "Heizleiter (NiCr-Drähte in Toaster, Föhn, Heizgeräten)", "Edelstahl-Legierungen", "Lederherstellung"], compounds: ["Cr₂O₃", "K₂Cr₂O₇", "CrO₃", "FeCr₂O₄"]),
        Element(z: 25, symbol: "Mn", col: 7, row: 4, category: .transition, nameDE: "Mangan", nameFR: "Manganèse", nameEN: "Manganese", nameLA: "Manganum", protons: 25, neutrons: 30, electrons: 25, mass: 54.938, meltingPointC: 1246, boilingPointC: 2061, stateAt20C: "fest", techApplications: ["Elektrotechnik: Alkali-Mangan-Batterien", "Lithium-Mangan-Akkus", "Stahllegierungen (Manganstahl)", "Aluminiumlegierungen"], compounds: ["MnO₂ (Braunstein)", "KMnO₄ (Kaliumpermanganat)", "MnCl₂", "MnSO₄"]),
        Element(z: 26, symbol: "Fe", col: 8, row: 4, category: .transition, nameDE: "Eisen", nameFR: "Fer", nameEN: "Iron", nameLA: "Ferrum", protons: 26, neutrons: 30, electrons: 26, mass: 55.845, meltingPointC: 1538, boilingPointC: 2862, stateAt20C: "fest", techApplications: ["Elektrotechnik: Eisenkerne in Transformatoren & Drosseln", "Elektromagnete, Relais, Motoren", "Ferrite in HF-Bauteilen & Antennen", "Stahl im Bauwesen"], compounds: ["Fe₂O₃ (Hämatit)", "Fe₃O₄ (Magnetit)", "FeS₂ (Pyrit)", "FeCl₃", "FeSO₄"]),
        Element(z: 27, symbol: "Co", col: 9, row: 4, category: .transition, nameDE: "Kobalt", nameFR: "Cobalt", nameEN: "Cobalt", nameLA: "Cobaltum", protons: 27, neutrons: 32, electrons: 27, mass: 58.933, meltingPointC: 1495, boilingPointC: 2927, stateAt20C: "fest", techApplications: ["Elektrotechnik: Lithium-Cobalt-Oxid in Lithium-Ionen-Akkus", "SmCo-Permanentmagnete (Hochtemperatur)", "Hartmetalle (WC-Co)", "Blaupigmente"], compounds: ["CoO", "Co₃O₄", "CoCl₂", "LiCoO₂"]),
        Element(z: 28, symbol: "Ni", col: 10, row: 4, category: .transition, nameDE: "Nickel", nameFR: "Nickel", nameEN: "Nickel", nameLA: "Niccolum", protons: 28, neutrons: 31, electrons: 28, mass: 58.693, meltingPointC: 1455, boilingPointC: 2913, stateAt20C: "fest", techApplications: ["Elektrotechnik: NiMH- & NiCd-Akkus", "Edelstahl, Münzen", "Vernickelung von Kontakten", "Heizdrähte (NiCr)"], compounds: ["NiO", "NiCl₂", "NiSO₄", "Ni(OH)₂"]),
        Element(z: 29, symbol: "Cu", col: 11, row: 4, category: .transition, nameDE: "Kupfer", nameFR: "Cuivre", nameEN: "Copper", nameLA: "Cuprum", protons: 29, neutrons: 35, electrons: 29, mass: 63.546, meltingPointC: 1084.62, boilingPointC: 2562, stateAt20C: "fest", techApplications: ["Elektrotechnik: Standard-Leitermaterial (Kabel, Wicklungen, Leiterbahnen)", "Transformatorenwicklungen", "Wärmetauscher", "Dachbedeckung"], compounds: ["CuSO₄", "Cu₂O", "CuO", "CuCl₂"]),
        Element(z: 30, symbol: "Zn", col: 12, row: 4, category: .transition, nameDE: "Zink", nameFR: "Zinc", nameEN: "Zinc", nameLA: "Zincum", protons: 30, neutrons: 35, electrons: 30, mass: 65.38, meltingPointC: 419.53, boilingPointC: 907, stateAt20C: "fest", techApplications: ["Elektrotechnik: Anode in Zink-Kohle- & Alkalibatterien", "Verzinkung von Stahl (Korrosionsschutz)", "Messing-Legierungen", "Druckguss"], compounds: ["ZnO", "ZnS (Zinkblende)", "ZnCl₂", "ZnSO₄"]),
    ]
}
