// AUTO-GENERATED. Do not edit by hand.
// Quelle: index.html (Tom BLEYER, 05/2026)

import Foundation

extension ElementsData {
    static let part_31_60: [Element] = [
        Element(z: 31, symbol: "Ga", col: 13, row: 4, category: .posttransition, nameDE: "Gallium", nameFR: "Gallium", nameEN: "Gallium", nameLA: "Gallium", protons: 31, neutrons: 39, electrons: 31, mass: 69.723, meltingPointC: 29.76, boilingPointC: 2204, stateAt20C: "fest", techApplications: ["Elektrotechnik: Galliumarsenid (GaAs) in Hochfrequenz-ICs (Mobilfunk, Radar)", "Galliumnitrid (GaN) in LEDs, Ladegeräten, 5G", "Solarzellen", "Halbleiterlaser"], compounds: ["GaAs", "GaN", "Ga₂O₃", "GaCl₃"]),
        Element(z: 32, symbol: "Ge", col: 14, row: 4, category: .metalloid, nameDE: "Germanium", nameFR: "Germanium", nameEN: "Germanium", nameLA: "Germanium", protons: 32, neutrons: 41, electrons: 32, mass: 72.63, meltingPointC: 938.25, boilingPointC: 2833, stateAt20C: "fest", techApplications: ["Elektrotechnik: Erste Halbleiterdioden & Transistoren", "SiGe-Heterostrukturen in Hochfrequenz-ICs", "Infrarot-Optik", "Glasfasern (Brechungsindex)"], compounds: ["GeO₂", "GeCl₄", "GeH₄"]),
        Element(z: 33, symbol: "As", col: 15, row: 4, category: .metalloid, nameDE: "Arsen", nameFR: "Arsenic", nameEN: "Arsenic", nameLA: "Arsenicum", protons: 33, neutrons: 42, electrons: 33, mass: 74.922, meltingPointC: 817, boilingPointC: 614, stateAt20C: "fest", techApplications: ["Elektrotechnik: Galliumarsenid (GaAs) in Hochleistungs-Halbleitern", "Dotierung von Silizium", "Bleilegierungen für Akkugitter"], compounds: ["As₂O₃", "AsH₃ (Arsin)", "GaAs", "Na₃AsO₄"]),
        Element(z: 34, symbol: "Se", col: 16, row: 4, category: .nonmetal, nameDE: "Selen", nameFR: "Sélénium", nameEN: "Selenium", nameLA: "Selenium", protons: 34, neutrons: 45, electrons: 34, mass: 78.971, meltingPointC: 221, boilingPointC: 685, stateAt20C: "fest", techApplications: ["Elektrotechnik: Photozellen & Belichtungsmesser", "Selen-Gleichrichter (historisch)", "CIGS-Solarzellen", "Xerografie (Trommeln in Kopierern)"], compounds: ["SeO₂", "H₂SeO₄", "CdSe", "Na₂SeO₃"]),
        Element(z: 35, symbol: "Br", col: 17, row: 4, category: .halogen, nameDE: "Brom", nameFR: "Brome", nameEN: "Bromine", nameLA: "Bromum", protons: 35, neutrons: 45, electrons: 35, mass: 79.904, meltingPointC: -7.2, boilingPointC: 58.8, stateAt20C: "flüssig", techApplications: ["Elektrotechnik: Bromhaltige Flammschutzmittel in Leiterplatten & Gehäusen", "Zink-Brom-Flussbatterien", "Bohrflüssigkeiten"], compounds: ["NaBr", "KBr", "HBr", "AgBr (Filmemulsion)"]),
        Element(z: 36, symbol: "Kr", col: 18, row: 4, category: .noblegas, nameDE: "Krypton", nameFR: "Krypton", nameEN: "Krypton", nameLA: "Krypton", protons: 36, neutrons: 48, electrons: 36, mass: 83.798, meltingPointC: -157.36, boilingPointC: -153.22, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: Füllgas in Energiesparlampen, Glühbirnen & Blitzlampen", "Kryptonlaser", "Hochleistungs-Isolierglas"], compounds: ["KrF₂ (instabil)", "Sonst keine stabilen Verbindungen"]),
        Element(z: 37, symbol: "Rb", col: 1, row: 5, category: .alkali, nameDE: "Rubidium", nameFR: "Rubidium", nameEN: "Rubidium", nameLA: "Rubidium", protons: 37, neutrons: 48, electrons: 37, mass: 85.468, meltingPointC: 39.31, boilingPointC: 688, stateAt20C: "fest", techApplications: ["Elektrotechnik: Atomuhren (Frequenznormale in GPS, Mobilfunk)", "Photozellen", "Spezialgläser"], compounds: ["RbCl", "Rb₂O", "RbOH"]),
        Element(z: 38, symbol: "Sr", col: 2, row: 5, category: .alkaline, nameDE: "Strontium", nameFR: "Strontium", nameEN: "Strontium", nameLA: "Strontium", protons: 38, neutrons: 50, electrons: 38, mass: 87.62, meltingPointC: 777, boilingPointC: 1382, stateAt20C: "fest", techApplications: ["Elektrotechnik: Strontiumferrite in Lautsprecher-Magneten", "Bildröhren-Glas (historisch)", "Pyrotechnik (rote Flamme)", "Keramikkondensatoren"], compounds: ["SrCO₃", "SrO", "SrSO₄ (Coelestin)", "SrCl₂"]),
        Element(z: 39, symbol: "Y", col: 3, row: 5, category: .transition, nameDE: "Yttrium", nameFR: "Yttrium", nameEN: "Yttrium", nameLA: "Yttrium", protons: 39, neutrons: 50, electrons: 39, mass: 88.906, meltingPointC: 1526, boilingPointC: 3336, stateAt20C: "fest", techApplications: ["Elektrotechnik: YBCO-Hochtemperatur-Supraleiter", "Phosphore in LED & Bildschirmen (Y₂O₃:Eu)", "YAG-Laserkristalle", "Mikrowellenfilter"], compounds: ["Y₂O₃", "YBa₂Cu₃O₇", "YCl₃"]),
        Element(z: 40, symbol: "Zr", col: 4, row: 5, category: .transition, nameDE: "Zirconium", nameFR: "Zirconium", nameEN: "Zirconium", nameLA: "Zirconium", protons: 40, neutrons: 51, electrons: 40, mass: 91.224, meltingPointC: 1855, boilingPointC: 4377, stateAt20C: "fest", techApplications: ["Elektrotechnik: Hüllrohre für Brennstäbe in Kernreaktoren", "Piezoelektrische Keramik (PZT) für Sensoren & Aktoren", "Keramische Kondensatoren", "Zahnersatz"], compounds: ["ZrO₂ (Zirkonia)", "ZrSiO₄ (Zirkon)", "ZrCl₄"]),
        Element(z: 41, symbol: "Nb", col: 5, row: 5, category: .transition, nameDE: "Niob", nameFR: "Niobium", nameEN: "Niobium", nameLA: "Niobium", protons: 41, neutrons: 52, electrons: 41, mass: 92.906, meltingPointC: 2477, boilingPointC: 4744, stateAt20C: "fest", techApplications: ["Elektrotechnik: Niob-Zinn (Nb₃Sn) Supraleiter in MRT- & LHC-Magneten", "Hochleistungs-Tantalkondensator-Ersatz", "Stahllegierungen für Pipelines"], compounds: ["Nb₂O₅", "NbCl₅", "Nb₃Sn"]),
        Element(z: 42, symbol: "Mo", col: 6, row: 5, category: .transition, nameDE: "Molybdän", nameFR: "Molybdène", nameEN: "Molybdenum", nameLA: "Molybdaenum", protons: 42, neutrons: 54, electrons: 42, mass: 95.95, meltingPointC: 2623, boilingPointC: 4639, stateAt20C: "fest", techApplications: ["Elektrotechnik: Elektroden in Glasschmelzen & Glühlampen", "MoSi₂-Heizelemente in Hochtemperaturöfen", "Stahllegierungen", "Schmiermittel (MoS₂)"], compounds: ["MoO₃", "MoS₂", "Na₂MoO₄"]),
        Element(z: 43, symbol: "Tc", col: 7, row: 5, category: .transition, nameDE: "Technetium", nameFR: "Technétium", nameEN: "Technetium", nameLA: "Technetium", protons: 43, neutrons: 55, electrons: 43, mass: 98.0, meltingPointC: 2157, boilingPointC: 4265, stateAt20C: "fest", techApplications: ["Elektrotechnik: kaum technisch (radioaktiv)", "Korrosionsschutzbeschichtungen (Forschung)", "Medizin: Tc-99m als Tracer in Szintigrafie"], compounds: ["TcO₄⁻ (Pertechnetat)", "Tc₂O₇"]),
        Element(z: 44, symbol: "Ru", col: 8, row: 5, category: .transition, nameDE: "Ruthenium", nameFR: "Ruthénium", nameEN: "Ruthenium", nameLA: "Ruthenium", protons: 44, neutrons: 57, electrons: 44, mass: 101.07, meltingPointC: 2334, boilingPointC: 4150, stateAt20C: "fest", techApplications: ["Elektrotechnik: Beschichtung von Festplatten (höhere Datendichte)", "Elektroden in Chloralkali-Elektrolyse", "Dickfilm-Widerstände", "Schmuck-Legierungen"], compounds: ["RuO₂", "RuO₄", "RuCl₃"]),
        Element(z: 45, symbol: "Rh", col: 9, row: 5, category: .transition, nameDE: "Rhodium", nameFR: "Rhodium", nameEN: "Rhodium", nameLA: "Rhodium", protons: 45, neutrons: 58, electrons: 45, mass: 102.91, meltingPointC: 1964, boilingPointC: 3695, stateAt20C: "fest", techApplications: ["Elektrotechnik: Beschichtung von Steckkontakten (sehr verschleißfest)", "Thermoelemente Pt/Rh", "Katalysator in Fahrzeug-Katalysatoren", "Schmuck"], compounds: ["Rh₂O₃", "RhCl₃"]),
        Element(z: 46, symbol: "Pd", col: 10, row: 5, category: .transition, nameDE: "Palladium", nameFR: "Palladium", nameEN: "Palladium", nameLA: "Palladium", protons: 46, neutrons: 60, electrons: 46, mass: 106.42, meltingPointC: 1554.9, boilingPointC: 2963, stateAt20C: "fest", techApplications: ["Elektrotechnik: Mehrschicht-Keramikkondensatoren (MLCC)", "Steckverbinderbeschichtung", "Wasserstoffspeicher", "Kfz-Katalysatoren", "Schmuck"], compounds: ["PdO", "PdCl₂"]),
        Element(z: 47, symbol: "Ag", col: 11, row: 5, category: .transition, nameDE: "Silber", nameFR: "Argent", nameEN: "Silver", nameLA: "Argentum", protons: 47, neutrons: 61, electrons: 47, mass: 107.87, meltingPointC: 961.78, boilingPointC: 2162, stateAt20C: "fest", techApplications: ["Elektrotechnik: Beste elektrische Leitfähigkeit – Hochfrequenz-Kontakte, Relais", "Lötlegierungen (Hartlot)", "Photovoltaik (Kontaktfinger)", "Spiegel, Schmuck, Münzen"], compounds: ["AgNO₃", "AgCl", "Ag₂O", "Ag₂S"]),
        Element(z: 48, symbol: "Cd", col: 12, row: 5, category: .transition, nameDE: "Cadmium", nameFR: "Cadmium", nameEN: "Cadmium", nameLA: "Cadmium", protons: 48, neutrons: 64, electrons: 48, mass: 112.41, meltingPointC: 321.07, boilingPointC: 767, stateAt20C: "fest", techApplications: ["Elektrotechnik: NiCd-Akkus (Memory-Effekt, RoHS-beschränkt)", "CdTe-Solarzellen", "Pigmente (Cadmiumgelb)", "Korrosionsschutz"], compounds: ["CdO", "CdS", "CdSe", "CdTe"]),
        Element(z: 49, symbol: "In", col: 13, row: 5, category: .posttransition, nameDE: "Indium", nameFR: "Indium", nameEN: "Indium", nameLA: "Indium", protons: 49, neutrons: 66, electrons: 49, mass: 114.82, meltingPointC: 156.6, boilingPointC: 2072, stateAt20C: "fest", techApplications: ["Elektrotechnik: ITO (Indium-Zinn-Oxid) für transparente Elektroden in Touchscreens, OLEDs, Solarzellen", "Lötlote (niedrigschmelzend)", "CIGS-Solarzellen", "Halbleiter (InP, InGaAs)"], compounds: ["In₂O₃", "InCl₃", "InP", "InGaAs"]),
        Element(z: 50, symbol: "Sn", col: 14, row: 5, category: .posttransition, nameDE: "Zinn", nameFR: "Étain", nameEN: "Tin", nameLA: "Stannum", protons: 50, neutrons: 69, electrons: 50, mass: 118.71, meltingPointC: 231.93, boilingPointC: 2602, stateAt20C: "fest", techApplications: ["Elektrotechnik: Weichlot (Sn-Cu, Sn-Ag-Cu für SMD-Bestückung)", "Verzinnung von Kupferdrähten", "Bronze", "Konservendosen", "Float-Glas-Bad"], compounds: ["SnO₂", "SnCl₂", "SnS"]),
        Element(z: 51, symbol: "Sb", col: 15, row: 5, category: .metalloid, nameDE: "Antimon", nameFR: "Antimoine", nameEN: "Antimony", nameLA: "Stibium", protons: 51, neutrons: 71, electrons: 51, mass: 121.76, meltingPointC: 630.63, boilingPointC: 1635, stateAt20C: "fest", techApplications: ["Elektrotechnik: Halbleiterlegierungen (InSb-Infrarotsensoren)", "Bleibatterien (Härtung der Gitter)", "Flammschutzmittel (Sb₂O₃) in Kabeln", "Lagermetall"], compounds: ["Sb₂O₃", "Sb₂S₃", "SbCl₃", "InSb"]),
        Element(z: 52, symbol: "Te", col: 16, row: 5, category: .metalloid, nameDE: "Tellur", nameFR: "Tellure", nameEN: "Tellurium", nameLA: "Tellurium", protons: 52, neutrons: 76, electrons: 52, mass: 127.6, meltingPointC: 449.51, boilingPointC: 988, stateAt20C: "fest", techApplications: ["Elektrotechnik: CdTe-Solarzellen (Dünnschicht-PV)", "Phasenwechselspeicher (DVD-RW, Blu-ray)", "Thermoelektrische Generatoren (Bi₂Te₃)", "Vulkanisation"], compounds: ["TeO₂", "CdTe", "Bi₂Te₃", "H₂Te"]),
        Element(z: 53, symbol: "I", col: 17, row: 5, category: .halogen, nameDE: "Iod", nameFR: "Iode", nameEN: "Iodine", nameLA: "Iodum", protons: 53, neutrons: 74, electrons: 53, mass: 126.9, meltingPointC: 113.7, boilingPointC: 184.3, stateAt20C: "fest", techApplications: ["Elektrotechnik: Halogen-Glühlampen (Iod-Wolfram-Kreislauf)", "Polarisationsfilter (LCD-Bildschirme)", "Desinfektion", "Röntgenkontrastmittel"], compounds: ["KI", "NaI", "HI", "I₂", "AgI"]),
        Element(z: 54, symbol: "Xe", col: 18, row: 5, category: .noblegas, nameDE: "Xenon", nameFR: "Xénon", nameEN: "Xenon", nameLA: "Xenon", protons: 54, neutrons: 77, electrons: 54, mass: 131.29, meltingPointC: -111.75, boilingPointC: -108.10, stateAt20C: "gasförmig", techApplications: ["Elektrotechnik: Xenon-Hochdrucklampen (Kfz-Scheinwerfer, Beamer, IMAX)", "Ionentriebwerke in Satelliten", "Blitzlampen", "Anästhetikum"], compounds: ["XeF₂", "XeF₄", "XeO₃"]),
        Element(z: 55, symbol: "Cs", col: 1, row: 6, category: .alkali, nameDE: "Caesium", nameFR: "Césium", nameEN: "Caesium", nameLA: "Caesium", protons: 55, neutrons: 78, electrons: 55, mass: 132.91, meltingPointC: 28.5, boilingPointC: 671, stateAt20C: "fest", techApplications: ["Elektrotechnik: Cäsium-Atomuhren (Sekundendefinition, GPS)", "Photokathoden in Photomultipliern", "Bohrflüssigkeiten", "Ionentriebwerke"], compounds: ["CsCl", "Cs₂O", "CsOH"]),
        Element(z: 56, symbol: "Ba", col: 2, row: 6, category: .alkaline, nameDE: "Barium", nameFR: "Baryum", nameEN: "Barium", nameLA: "Barium", protons: 56, neutrons: 81, electrons: 56, mass: 137.33, meltingPointC: 727, boilingPointC: 1897, stateAt20C: "fest", techApplications: ["Elektrotechnik: BaTiO₃ als Dielektrikum in Keramikkondensatoren & Piezoelementen", "YBCO-Supraleiter", "Bildröhren-Glas (historisch)", "Pyrotechnik (grün)"], compounds: ["BaSO₄", "BaCO₃", "BaTiO₃", "BaCl₂"]),
        Element(z: 57, symbol: "La", col: 3, row: 6, category: .lanthanide, nameDE: "Lanthan", nameFR: "Lanthane", nameEN: "Lanthanum", nameLA: "Lanthanum", protons: 57, neutrons: 82, electrons: 57, mass: 138.91, meltingPointC: 920, boilingPointC: 3464, stateAt20C: "fest", techApplications: ["Elektrotechnik: NiMH-Akkus (Anodenmaterial)", "Hochbrechende Spezialgläser (Kameralinsen)", "Petroleum-Cracking-Katalysator", "Beleuchtungstechnik"], compounds: ["La₂O₃", "LaCl₃", "LaB₆"]),
        Element(z: 58, symbol: "Ce", col: 4, row: 6, category: .lanthanide, nameDE: "Cer", nameFR: "Cérium", nameEN: "Cerium", nameLA: "Cerium", protons: 58, neutrons: 82, electrons: 58, mass: 140.12, meltingPointC: 799, boilingPointC: 3443, stateAt20C: "fest", techApplications: ["Elektrotechnik: Polierpulver für Bildschirmglas & Halbleiter-Wafer", "Leuchtstoffe in LEDs (YAG:Ce)", "Auto-Katalysatoren", "Feuersteine (Mischmetall)"], compounds: ["CeO₂", "Ce₂O₃", "CeCl₃"]),
        Element(z: 59, symbol: "Pr", col: 5, row: 6, category: .lanthanide, nameDE: "Praseodym", nameFR: "Praséodyme", nameEN: "Praseodymium", nameLA: "Praseodymium", protons: 59, neutrons: 82, electrons: 59, mass: 140.91, meltingPointC: 931, boilingPointC: 3520, stateAt20C: "fest", techApplications: ["Elektrotechnik: Permanentmagnete (Pr-Nd-Fe-B) in E-Motoren & Festplatten", "Glasfärbung (gelbgrün)", "Faseroptik-Verstärker"], compounds: ["Pr₂O₃", "PrCl₃"]),
        Element(z: 60, symbol: "Nd", col: 6, row: 6, category: .lanthanide, nameDE: "Neodym", nameFR: "Néodyme", nameEN: "Neodymium", nameLA: "Neodymium", protons: 60, neutrons: 84, electrons: 60, mass: 144.24, meltingPointC: 1016, boilingPointC: 3074, stateAt20C: "fest", techApplications: ["Elektrotechnik: Stärkste Permanentmagnete (Nd₂Fe₁₄B) in Festplatten, Kopfhörern, Windturbinen & E-Auto-Motoren", "Nd:YAG-Laser", "Glasfärbung"], compounds: ["Nd₂O₃", "NdCl₃", "Nd₂Fe₁₄B"]),
    ]
}
